Updated Polymer library

diff --git a/html/bower_components/iron-dropdown/.travis.yml b/html/bower_components/iron-dropdown/.travis.yml
--- a/html/bower_components/iron-dropdown/.travis.yml
+++ b/html/bower_components/iron-dropdown/.travis.yml
@@ -1,5 +1,5 @@
 language: node_js
-sudo: required
+sudo: 'false'
 before_script:
   - npm install -g polymer-cli
   - polymer install --variants
@@ -7,23 +7,25 @@ before_script:
     npm run update-types && git diff --exit-code || (echo -e
     '\n\033[31mERROR:\033[0m Typings are stale. Please run "npm run
     update-types".' && false)
+  - >-
+    npm run format && git diff --exit-code || (echo -e '\n\033[31mERROR:\033[0m
+    Project is not formatted. Please run "npm run format".' && false)
 env:
   global:
     - secure: >-
-        YMlrRxFp8QBJ9KfvrPru2sIaHm5GeVHsZ/wE4qm5ntdsoqQlsJXRYYhlE2jPSHte+2VrOnFItjCsoqG6myeCbMrDS+/ZAZd+PWNdxbSs0DiGVMJWtrd8PwhKeOoVYzJleTwU0Uj2mF/mKwoC6aNgf56V9XzC2mkooRJX9cDbCkfddcIGoU/45zsPPMJV+BRVDcETw5g0PD+7NJBPtJP+d8TMO+jtdgXQ1V0vPJhkS7RaYZoDeljsml/Xc8Djb3zUttu5cFk4lXeKAKtFgFzxVsFqytxuYY2aSkMcq2/KxwexnnK/SCe5uQC014TjYAMzSs5A7l/ZBEzRGDhxKmkR2JHY3ktRCOFphqrQa9JoK3k+Tc28JeXJXTXNW7B5SODclN45ik5jQQ/FaJgRlideK07LsEObC9FjEoSd0U5rt75bzIhGuBQ6vr16JQLtN7+NvPRMsNqZRGHQysbW7SbfuLdWwmprn8kXaiQoensAnWlrrGoaPtPfKgA68YRQ/2cr9zZWFmMTzfDP6/Y8YSulj1mzqP2U8AZStXZ1vKN7IWY/ADzYrRG/nCqwd8gQpQoiAEgOfc+de5fIzLPRfLS8fI8sow9yZC8hE91JDatxOPvg/YCDGfJUQddCG+Z3LIBqY6RYKjXzCTCexGD6XWIJso8x5HEEWEQKArqT6vLM4gE=
+        F057FJvYu8+IwJcHCVTmLKvuBcfVt13hfYENjr4SOJzR3nNjUi0KjPiHI6tO6EhqYHbaO7cO2vORlennyDFLdq/Q2o+xkcbus8MvkMgGd+ThcZdQY+OItSAamq7kwkDXIpGpRiTzYmWZgoQWZwyqPZQL1diZ7sWcaUCcAIkuLajTIslKPJHNLwHldBxxztxNA/fqNn0fCl+c8zxZzmRhxuqGGEFFaNqPLZfBP4/irKntTJ1+E2aOmK9CFEXWUeV+GySHee6DZxtgakAjcB7/7SYxyMiPQOMOtz6mNFm/7vHoZpsb139itDB0UTcs/39oTWG4ltn4651SLhhPdP0HS4VhhdAq4cM2faPh44lPlIhdUGCoiFW+MOPnQ1/96zF605fa0mhf54bsPJgQhBcMl9rVUkqGnH1GS+mLdAqXWz0UnQ3oxz9WFUNWwDhcSkw1vZ/aNVMgkFOFyt8nB27ZkFiYCj8LrVfUnN5qHRQwViB0Tk5zJgAvdWoRIqm1aqgNFbspXjf3qOtyi7D7b5y/pFBXYYxt9T8H9cQQnq+kBaSz9Vqymo174slDMCNIthYl7q4A4volIscxyIPGY3v7VCyW62C2OaY/BC2a1mKq6+3e/z2KBrBuLSDPoAHpirwENcAes4jo8+V5uxCyjKOes1f0hfy6y+KZlWh7rMFDZPM=
     - secure: >-
-        yNGht7DLQ56gIwWh+Wu/3spWaIo0qR/EXB7SDzGtE7Y1KLbgYjmGCnA+3Y+vQ8q9Smpv66FMi8ejbBnObb347806LykEG23OJWBbruUi3gGoImNqLmaj+iqxiaYzxqIWs7gwhpYMdNGFiu1T83eBLOLoVQqO1OIIVbH1Fk0MvHvbknY52VyOEaEjVBdnWAxTpDdgujzVaPBxaPCbD15nUFgaMCsBdR0SKtX0X+vVZRdu0VzHqLJPhUxrQJIxdAYc/OyEKki5pR93b0df+0P14NHxduWNtaAReBtMtpVsiLfaxiHdoWzjHdJ2g+x4DEoH1ynbs4v/8qWE1xLABcgHK2UeZYwTtk7KSA9ZcYSx7JxnO1mhseWdiCSKO4Y0bZuBcSsQ9O5skvIOhAd9bLdQHMe4bHSf8mhtv/Kw6IHmEqZ9YZ8TIk7YY4bYiLOKsN6q2kYbWO7UVeYBLul3mppiEWZ04JmbjVU5us1hq40RdSsc34/fW3KitLfVaYQlTWlZ/h9nx7tOQ2o6OOSHgRnD8qPpFM+xExqkj2FIgUWyecn8VKQ6FojgfOeVyEQ3WdPK17LdFxhKfHVod+Qufl6ArBsUMWctns4/jQTCJXL+VIPfZWQ/wrYmkIW7dEjA6NnTMBqhjBa37C1G8+Ak5kvSAcU4iAbjqA1jVv4RANRV5x8=
-node_js: stable
+        H9qozidVoLTnEkMMVONgl0/TxSZ1F4gfRYtxmFu9PgDmz+lkX/BGI8iiAYSSW7Yv77fJ8idS7npnv4JYwLU7PlTY50xyxSjhO6vau/1lSGlTHgAXvqAhNrRu3GVgaddyWA0+e+rTGdK+l3QInIX68qKmTui7lG/BJIiiSZfX61FhFrIQqngl8Q3D4IiuQTIxuZuTckbou/a1/yMgCG9V49cbP5UeA/TEMmspQ109/OqJDVxWrKi7t4FA9fVRbMQ1QPu8tdMUBRHTMzgCPjDZZ69JQixDD0qwhfygER9WH3/BI5dkzByTbBQsUkM9Kl7SGH1dRmfVpeO4rt8qkSw10qR3e505G2OYajCxteloRTCKD0x6Yk2haW/U3v9IwjzbYzkqTrsJJYmpQwUumbfJHJ/eANxRddC6gMzuetraIBUco+qwdQlXQRXque8CyoTNgoX2mCJKPvd/AUE1EAX4F712SLx+enNjj2IoKN3dKnmngigKcPyo2o9u4zeon/Y3WGigXTpz6vRzUbb+v5oYCbcuACojyM4t5wKsehoE7zsLvPXkFQZXlkn4yaLBEsgNEWhfT6gk3bLPktZBAbKs8ozIW/DgtKJZ+VZOPJ33QhFASB6Bw9awrdqW6uYrv/zb1biNxUUN2codurTrkmYuvyHWGdtMnB2vIJj6P8UVCQk=
+node_js: '9'
 addons:
   firefox: latest
-  apt:
-    sources:
-      - google-chrome
-    packages:
-      - google-chrome-stable
+  chrome: stable
 script:
   - xvfb-run polymer test
   - >-
     if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default';
     fi
 dist: trusty
+cache:
+  directories:
+    - node_modules
diff --git a/html/bower_components/paper-button/.travis.yml b/html/bower_components/paper-button/.travis.yml
--- a/html/bower_components/paper-button/.travis.yml
+++ b/html/bower_components/paper-button/.travis.yml
@@ -1,5 +1,5 @@
 language: node_js
-sudo: required
+sudo: 'false'
 before_script:
   - npm install -g polymer-cli
   - polymer install --variants
@@ -7,24 +7,25 @@ before_script:
     npm run update-types && git diff --exit-code || (echo -e
     '\n\033[31mERROR:\033[0m Typings are stale. Please run "npm run
     update-types".' && false)
+  - >-
+    npm run format && git diff --exit-code || (echo -e '\n\033[31mERROR:\033[0m
+    Project is not formatted. Please run "npm run format".' && false)
 env:
   global:
     - secure: >-
-        YhRb8f1f4y3Rjs5wnp4sCzIcEcL07HOBoJcEp6U/KVgIIk/sBxkxMVmZsoUeABrNbKcdE6Gn6OS2K1lFq4VThKppJ0yjvESa1p0FjmQ0Nf1xCYxc46n936xj87khZy3rrTGHxwcOY5vAa5mvNzXI4BYxjmSjmqRsQwsJBsJHWVw=
+        UCS5TSfKVWi6c8j/jJZPOX7JvLPxs2GiEua2lZOrgFD2U+SPk3oIToOJ3j/ItMdK2imcrHOtA369sEyYZbrUQVAu+XWX3B2xar5VK8uD12Mw57D1eq1WAQ5qKiDBQ4b0rhuYm2LX7pQhtU8YgUHrXs60GT8YXW0T+NeRieXHRas=
     - secure: >-
-        eQjSTRxQKF5vyRa6yK2o+j5xWK480hHCKDh7RJQISEVhyzAaCzPZNmWf2pmaDj+ZoZZrahBcoRwOZAiVdHDaKQ+VLHbEECzV3OVV32/9DHi608BPCBdxVR2MDTtZVt3fGVhPQwCnFhwRTWtVVGx8y8HnTDMv/r4xW1OMSThPsbM=
-node_js: stable
+        dX4A2hHUV0UUtwONe4JjODrq5BFS1d7z8WUZgoXsaPV+t4spnZOSMLCfruKu83MH1qIJltvZArMN0jcXUuiF2/tU0JffuwS1wqjNhp7LVfn0cAOQVx/XgS8+yzgKoHgbSRgb1dGvjPv4VJX5OdzCrH+asfBUegmK9XCvVPw5wOM=
+node_js: '9'
 addons:
   firefox: latest
-  apt:
-    sources:
-      - google-chrome
-    packages:
-      - google-chrome-stable
-  sauce_connect: true
+  chrome: stable
 script:
   - xvfb-run polymer test
   - >-
     if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default';
     fi
 dist: trusty
+cache:
+  directories:
+    - node_modules
diff --git a/html/bower_components/paper-drawer-panel/.travis.yml b/html/bower_components/paper-drawer-panel/.travis.yml
--- a/html/bower_components/paper-drawer-panel/.travis.yml
+++ b/html/bower_components/paper-drawer-panel/.travis.yml
@@ -1,5 +1,5 @@
 language: node_js
-sudo: required
+sudo: 'false'
 before_script:
   - npm install -g polymer-cli
   - polymer install --variants
@@ -7,23 +7,25 @@ before_script:
     npm run update-types && git diff --exit-code || (echo -e
     '\n\033[31mERROR:\033[0m Typings are stale. Please run "npm run
     update-types".' && false)
+  - >-
+    npm run format && git diff --exit-code || (echo -e '\n\033[31mERROR:\033[0m
+    Project is not formatted. Please run "npm run format".' && false)
 env:
   global:
     - secure: >-
-        dUMG4gWauTfBoni97er7PvM3qQ4bcAf7J2PvSIe/F8b1NX4rwf6dlAkUUoDAru8C7UTSpveWGgZgTFsIzn+UNKsnjWMR20oqxYD56cUInNsDdd3rC7jj7Asyfi3ULxkgcNRMm0MAelEnp6Q57GS1OpGRt6sMJoEVI62YodgQE9s=
+        W0u2EpJosSjej3eqaOWOjcibtqoD42mKoZfRE9UlAiBuZJzIut/245LQdYsRODn2H4lFahCFfviEXbhJNWhDWwVmhXEWzWzbQYs9ztSDMkMfMIYcGFBfxMfxK4BSPQgVs6riAY5upUV93rABz4mggymLQfOlOSaumziy9lPiN6Y=
     - secure: >-
-        ae6sSw/OJyyGVzljBsok9KLi0BV+r4IvbvjVPGYaG2TtqR+JonyEu9OI2V/DgAJJ3RHQo0W/go4NcZlQmMb17gNCuqxWVeG/Tf2DH/QJr7RR9bUhYwOJTRR4dzXvaEgLiLOZG5grOGaM2pVQETnTIrLQtic2O18uhM8Ro2oV//s=
-node_js: stable
+        dPF0yCGYWrDHnOtcSmuUv5N91UhrUJ/Y8eqTZTLOokuF4uSWgmR2xK2OQvhbEjq7b1O1iqNWIZ+rpwVlchuH4FNWBibZ9L0bpqZDshRvSFoGpJwdOUehiQJUjhJ1+DjALYArIhe4R4mVOp56Ci+qzoYb8AxJP1p1ePVZgvFFjR4=
+node_js: '9'
 addons:
   firefox: latest
-  apt:
-    sources:
-      - google-chrome
-    packages:
-      - google-chrome-stable
+  chrome: stable
 script:
   - xvfb-run polymer test
   - >-
     if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default';
     fi
 dist: trusty
+cache:
+  directories:
+    - node_modules
diff --git a/html/bower_components/paper-slider/.travis.yml b/html/bower_components/paper-slider/.travis.yml
--- a/html/bower_components/paper-slider/.travis.yml
+++ b/html/bower_components/paper-slider/.travis.yml
@@ -1,25 +1,31 @@
 language: node_js
-sudo: required
+sudo: 'false'
 before_script:
   - npm install -g polymer-cli
   - polymer install --variants
+  - >-
+    npm run update-types && git diff --exit-code || (echo -e
+    '\n\033[31mERROR:\033[0m Typings are stale. Please run "npm run
+    update-types".' && false)
+  - >-
+    npm run format && git diff --exit-code || (echo -e '\n\033[31mERROR:\033[0m
+    Project is not formatted. Please run "npm run format".' && false)
 env:
   global:
     - secure: >-
-        n4PzATQdbmNr0NAPZGYLQOWwu1UQXAtAxDTlM6b1eSwrBXBw7VNU8M+7Zs9Ho6LDBV7Wd8Ktjw6PCUkeIQUmiKrycz1p7Tthu7JsnUuEUKKCqzo0Vh41z7W63Cs7T1NryyMUXnnlen/VxMOyiQ6JA/yXl0TDavF5UoU/uXU+WsA62Fsv4+izv5hx37+2IK4bJZe4MKTr4euh0gcOqRWRwP+A7Tx8UAZYouvn7H0ho6ORRbP6OQfPxMHtbJPznDUNIvrkjtqCzOkFgQxncVBjzRcS2iKGb+8T2ax5zMUJpBX6Q1SwpY4Y0pAA1ZdFLI7tyiM+BwhoDLZqpePe5tAU024qEcohRUkY5/I3z9whyBF81/HOI9b5xZQnlwsPNBdwUdjgSUz8OGVflmBxBovuhlN7lCea/2HkHVmLA3k8r6Lpqax8JquNdjRY9IQdvJpLueWOeVYMi6TJfgIIpjXim6jVzTfICX3qH9mNjDoncQ96EhxM9Hq2O5bBBkKCJVvyXyrkeqvJPG6fnqAdDC9ybKL86VAgHBuYTKqHnjsRq+Cqy+kSu56pXzH3rTNmC3ixt2dScxluK3Z6ItmR4kfALltpYzKvElsWAx/r4hKqIkO+sBpLKXLafRiwx0J3zS/CpV2AWJNihaK/iVMRWD+8TDi9eZ/43Abc9d9Sw6AgnmU=
+        TunBXHMpmjUfz/kU0bIWd6X6ph1H2gxItZWrTrarjUeJnjf1CG/3IoTKO88EIsesUT55S3UUk05UofSx+CLGriwtpu007YYVNV91L+XXo5ruo/IdeNBUtyKZBu4wFMM5iNnI2h7JznYx74VjHBBVvq5unLykwHMVnBD3uH1pg7Xuaa7V/6EV1ebWU/CGYBWkUszdPv6RJjdriM/WCTkGu0is9ypDonCK9GFCnWm6yHyZ6EV5CLr97mMHjbi06hUAuKsxpnvcKhnv6kJRo6W5fgY4rDOmCgyzydtLbMoQSl0ZIdJIec2jehbWfoCUCq9WXPcI6GXDyyIp9f48DghtdcJ7IWKYqP8eTLzbOVTLE+J53oy18Rey4lf8CWuLw05HdlSjzGaF1UvKudhJGhjCKlf0QrJfGIrDpwhVYvY6AKB8toxm7QuqutiV5tvpN08zR6ABrY2xEQ8lf6j8HMg/ZxjiQcBYOtv4bUHQz24o2SoLROAg113lW1xI9/sn7lMbpKuJVehfT9/M11eVP/Vn44VQsJ/2FXHMm5XkQfyk4+4nJJNprosPU4e+vxe+wq5l/BipizTCmSIahcz9MJQNlaIOEGKvGOJPx5qdXBMB5u9+6liYCq6/VdBSojExdvswYZsBSsj/iql3FUMQOQ/9pUL/v1NkiSKMbBL/Csd3GTY=
     - secure: >-
-        YHkImXE3+PaTw/nL9boZcJA0TJZesmYZ0wsa1C6xGz0NEEVmn6R687N7SOklP13wjues5FwPlY2HehhLJDjn8c+vT/p02UWUr8CJmhyVkWrgufVDHSg6hopiKHroLvNxUOtbwVLQ2wYtQpgM8ru3DbvJKWgCtKbXo+7owz3TSAwD2ksaGUCjNnLQ8qXeSytLn8ck3WfPPIqJ+hA7ge63QNnglMRvPGQWKSt1rM0XyW+hZ0fbd5o/ng+4f1hwS2nIZGlM4WOQ2fTDoCRyVtZ1XfnL1uK6FoHMSunQ32T0j7n7qPGWof6W9Tl08TRk5ltPRBSzjfZt5BWD1bkfTm5Pme9X7rCHQ7Ddim54nmgvAXnWc/VflSgkn1FEdtAKcOh4zWzGX34PrYfzFgBIt8sVtvVO5Kletv+1cPxxHM804pxNtFqUjEKtBIBpFI2vS6yH+FyRX/oSQETAtFl6aCsxDW3MoeK5s9AMq7xnZ10mEC6SkCHRfkGh/rgDEsNsPYVXlpwxYiUEPWET7K2PxWyyNJYz6Qq2C5TcY7gvHIyvxbk7jnWgPZV0NzyFcCvch55mWA5/mM886w3+YDt06v1wWyKq41s4bWCWiql5UK5V9IgurZs65mBWTy7leztIe0lmipr9xn8rb5lPTQIrGdRGljBnEGthT4I7LLc/1Cj/iZI=
-node_js: stable
+        N+F324OMnxvjYS6gnlWacaf6uiyDc0m2O3xARjHoso/nLWLxPkrYItGA2YyGzyAhL2Fta0E3QS/3hN53jvO1DwDXht6ser2r8bLGolFD4MKhlWKFYJV7Te6WRA21lyLty/mx9YDw+DQIM6b3pa2DtkKEzp1+ho9pqIKnxxj2WbykSd0QVXeZKx5ZLIEWil7Ue875B6DaBxynK8KmYYF0elOmjy+Gx+cchH092YHrybqM4UYO9Zo/CamZgGHxbSwp6tI/gj1tFw/6kgtxdmuVAPYrQWG7C1ephV9av9DxtHuDRcKC8MI5lnBOS/jcfaQEOQMnzPI8Fe9pFezPA5eyAeCIGoxIoEG83uNQ6yXGcaPQm/Wv22VdPLYRzsp0xUixT5H/1lnrf0Sc0jM2j+pG1LIGa9Kn7RSImYvtRzKWO6x4gwlwLnrxffli8c1pskumzhpcfPVsKtzkCSZLvoHA/872BiPhKdG3jqbbBIH0IJA02TSfMn1+XxmVqD5MEmOVd56roTgjJXKeJ1wGSE1wO28neWbb0MR7wDe7iqrtNMIGHhIhrxFZ2JdgJuCILpKNj1Q1vdoomIJ4qNCo7jtxS9fISvyu7rq5iLQbTZhRJsLsvgq9JurJ9XuLZG0R9mJfGtJv5djpb8TlJ87272YvLsU1JIc9i/Q6EbjmAeaIdXI=
+node_js: '9'
 addons:
   firefox: latest
-  apt:
-    sources:
-      - google-chrome
-    packages:
-      - google-chrome-stable
+  chrome: stable
 script:
   - xvfb-run polymer test
   - >-
     if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default';
     fi
 dist: trusty
+cache:
+  directories:
+    - node_modules
